spring:
  datasource:
    username: root
    password: mogu2018
    url: jdbc:mysql://mysql:3306/halo_mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  application:
    name: halomall-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000